changelog: # リリースノートの設定
  exclude:
    labels:
      - "ignore for release"

  categories: # リリースノートのカテゴリーとラベル
    - title: Breaking Change
      labels: ["Type: Breaking Change"] # 互換性がない破壊的変更に対するラベル

    - title: Bug
      labels: ["Type: Bug"] # バグ修正に対するラベル

    - title: Documentation
      labels: ["Type: Documentation"] # ドキュメントの更新に対するラベル

    - title: Feature
      labels: ["Type: Feature"] # 新機能追加に対するラベル

    - title: Refactoring
      labels: ["Type: Refactoring"] # コードのリファクタリングに対するラベル

    - title: Testing
      labels: ["Type: Testing"] # テストの更新に対するラベル

    - title: Maintenance
      labels: ["Type: Maintenance"] # メンテナンスに対するラベル

    - title: Question
      labels: ["Type: Question"] # 質問や議論に対するラベル

    - title: Other Changes
      labels: ["*"] # その他の変更に対するラベル
